projects:
  node-react-starter:
    schemaPath: schema.graphql
    extensions:
      endpoints:
        dev:
          url: 'http://localhost:4000/graphql'
          subscription: 'ws://localhost:4000/graphql'